version: "3.8"

services:
  server-api:
    restart: always
    build: .
    container_name: disney
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: "mysql:5.7"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: disney
      MYSQL_USER: ignacio
      MYSQL_PASSWORD: ignacio
      MYSQL_ROOT_PASSWORD: ignacio
    restart: always
    healthcheck:
      test: "mysql -h mysqldb -u ignacio -pignacio -e 'SELECT 1'"
      interval: 1s
      retries: 20
    volumes:
      - mysqldb-data:/var/lib/mysql

volumes:
  mysqldb-data: