version: "3.8"

services:
  java-api:
    restart: always
    build: .
    image: java-api
    container_name: java-api
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - disney

  mysqldb:
    restart: always
    image: "mysql:5.7"
    container_name: mysqldb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: disney
      MYSQL_USER: ignacio
      MYSQL_PASSWORD: ignacio
      MYSQL_ROOT_PASSWORD: ignacio
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysqldb", "-u", "ignacio", "-pignacio" ]
      interval: 1s
      retries: 20
    volumes:
      - mysqldb-data:/var/lib/mysql
    networks:
      - disney

volumes:
  mysqldb-data:

networks:
  disney:
    driver: bridge